spring:
  application:
    name: marketplace-test
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:marketplace}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  jwt:
    secret: ${JWT_SECRET}  # Chave secreta para assinar o token
    expiration: 86400000                 # Tempo de expiração em ms (1 dia)
    refreshExpiration: 604800000         # Tempo refresh token (7 dias)

