spring:
  application:
    name: marketplace-test
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5332}/${DB_NAME:marketplace}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
